/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PredictRouteImport } from './routes/predict'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as GuildsRouteImport } from './routes/guilds'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayerPlayerRouteImport } from './routes/player/$player'
import { Route as GameGameRouteImport } from './routes/game/$game'
import { Route as CollectionCollectionRouteImport } from './routes/collection/$collection'
import { Route as PlayerPlayerIndexRouteImport } from './routes/player/$player/index'
import { Route as GameGameIndexRouteImport } from './routes/game/$game/index'
import { Route as CollectionCollectionIndexRouteImport } from './routes/collection/$collection/index'
import { Route as PlayerPlayerPositionsRouteImport } from './routes/player/$player/positions'
import { Route as PlayerPlayerInventoryRouteImport } from './routes/player/$player/inventory'
import { Route as PlayerPlayerActivityRouteImport } from './routes/player/$player/activity'
import { Route as PlayerPlayerAchievementsRouteImport } from './routes/player/$player/achievements'
import { Route as GameGamePredictRouteImport } from './routes/game/$game/predict'
import { Route as GameGameMarketplaceRouteImport } from './routes/game/$game/marketplace'
import { Route as GameGameLeaderboardRouteImport } from './routes/game/$game/leaderboard'
import { Route as GameGameInventoryRouteImport } from './routes/game/$game/inventory'
import { Route as GameGameGuildsRouteImport } from './routes/game/$game/guilds'
import { Route as GameGameActivityRouteImport } from './routes/game/$game/activity'
import { Route as GameGameAboutRouteImport } from './routes/game/$game/about'
import { Route as CollectionCollectionItemsRouteImport } from './routes/collection/$collection/items'
import { Route as CollectionCollectionHoldersRouteImport } from './routes/collection/$collection/holders'
import { Route as CollectionCollectionActivityRouteImport } from './routes/collection/$collection/activity'
import { Route as GameGamePlayerPlayerRouteImport } from './routes/game/$game_/player/$player'
import { Route as GameGameCollectionCollectionRouteImport } from './routes/game/$game/collection/$collection'
import { Route as GameGamePlayerPlayerIndexRouteImport } from './routes/game/$game_/player/$player/index'
import { Route as GameGameEditionEditionIndexRouteImport } from './routes/game/$game/edition/$edition/index'
import { Route as GameGameCollectionCollectionIndexRouteImport } from './routes/game/$game/collection/$collection/index'
import { Route as GameGamePlayerPlayerPositionsRouteImport } from './routes/game/$game_/player/$player/positions'
import { Route as GameGamePlayerPlayerInventoryRouteImport } from './routes/game/$game_/player/$player/inventory'
import { Route as GameGamePlayerPlayerActivityRouteImport } from './routes/game/$game_/player/$player/activity'
import { Route as GameGamePlayerPlayerAchievementsRouteImport } from './routes/game/$game_/player/$player/achievements'
import { Route as GameGameEditionEditionPredictRouteImport } from './routes/game/$game/edition/$edition/predict'
import { Route as GameGameEditionEditionMarketplaceRouteImport } from './routes/game/$game/edition/$edition/marketplace'
import { Route as GameGameEditionEditionLeaderboardRouteImport } from './routes/game/$game/edition/$edition/leaderboard'
import { Route as GameGameEditionEditionInventoryRouteImport } from './routes/game/$game/edition/$edition/inventory'
import { Route as GameGameEditionEditionGuildsRouteImport } from './routes/game/$game/edition/$edition/guilds'
import { Route as GameGameEditionEditionActivityRouteImport } from './routes/game/$game/edition/$edition/activity'
import { Route as GameGameEditionEditionAboutRouteImport } from './routes/game/$game/edition/$edition/about'
import { Route as GameGameCollectionCollectionItemsRouteImport } from './routes/game/$game/collection/$collection/items'
import { Route as GameGameCollectionCollectionHoldersRouteImport } from './routes/game/$game/collection/$collection/holders'
import { Route as GameGameCollectionCollectionActivityRouteImport } from './routes/game/$game/collection/$collection/activity'
import { Route as GameGameEditionEditionPlayerPlayerRouteImport } from './routes/game/$game_/edition/$edition_/player/$player'
import { Route as GameGameEditionEditionCollectionCollectionRouteImport } from './routes/game/$game_/edition/$edition_/collection/$collection'
import { Route as GameGameEditionEditionPlayerPlayerIndexRouteImport } from './routes/game/$game_/edition/$edition_/player/$player/index'
import { Route as GameGameEditionEditionCollectionCollectionIndexRouteImport } from './routes/game/$game_/edition/$edition_/collection/$collection/index'
import { Route as GameGameEditionEditionPlayerPlayerPositionsRouteImport } from './routes/game/$game_/edition/$edition_/player/$player/positions'
import { Route as GameGameEditionEditionPlayerPlayerInventoryRouteImport } from './routes/game/$game_/edition/$edition_/player/$player/inventory'
import { Route as GameGameEditionEditionPlayerPlayerActivityRouteImport } from './routes/game/$game_/edition/$edition_/player/$player/activity'
import { Route as GameGameEditionEditionPlayerPlayerAchievementsRouteImport } from './routes/game/$game_/edition/$edition_/player/$player/achievements'
import { Route as GameGameEditionEditionCollectionCollectionItemsRouteImport } from './routes/game/$game_/edition/$edition_/collection/$collection/items'
import { Route as GameGameEditionEditionCollectionCollectionHoldersRouteImport } from './routes/game/$game_/edition/$edition_/collection/$collection/holders'
import { Route as GameGameEditionEditionCollectionCollectionActivityRouteImport } from './routes/game/$game_/edition/$edition_/collection/$collection/activity'

const PredictRoute = PredictRouteImport.update({
  id: '/predict',
  path: '/predict',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const GuildsRoute = GuildsRouteImport.update({
  id: '/guilds',
  path: '/guilds',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerPlayerRoute = PlayerPlayerRouteImport.update({
  id: '/player/$player',
  path: '/player/$player',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameRoute = GameGameRouteImport.update({
  id: '/game/$game',
  path: '/game/$game',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionCollectionRoute = CollectionCollectionRouteImport.update({
  id: '/collection/$collection',
  path: '/collection/$collection',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerPlayerIndexRoute = PlayerPlayerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayerPlayerRoute,
} as any)
const GameGameIndexRoute = GameGameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GameGameRoute,
} as any)
const CollectionCollectionIndexRoute =
  CollectionCollectionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CollectionCollectionRoute,
  } as any)
const PlayerPlayerPositionsRoute = PlayerPlayerPositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => PlayerPlayerRoute,
} as any)
const PlayerPlayerInventoryRoute = PlayerPlayerInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => PlayerPlayerRoute,
} as any)
const PlayerPlayerActivityRoute = PlayerPlayerActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => PlayerPlayerRoute,
} as any)
const PlayerPlayerAchievementsRoute =
  PlayerPlayerAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => PlayerPlayerRoute,
  } as any)
const GameGamePredictRoute = GameGamePredictRouteImport.update({
  id: '/predict',
  path: '/predict',
  getParentRoute: () => GameGameRoute,
} as any)
const GameGameMarketplaceRoute = GameGameMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => GameGameRoute,
} as any)
const GameGameLeaderboardRoute = GameGameLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => GameGameRoute,
} as any)
const GameGameInventoryRoute = GameGameInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => GameGameRoute,
} as any)
const GameGameGuildsRoute = GameGameGuildsRouteImport.update({
  id: '/guilds',
  path: '/guilds',
  getParentRoute: () => GameGameRoute,
} as any)
const GameGameActivityRoute = GameGameActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => GameGameRoute,
} as any)
const GameGameAboutRoute = GameGameAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => GameGameRoute,
} as any)
const CollectionCollectionItemsRoute =
  CollectionCollectionItemsRouteImport.update({
    id: '/items',
    path: '/items',
    getParentRoute: () => CollectionCollectionRoute,
  } as any)
const CollectionCollectionHoldersRoute =
  CollectionCollectionHoldersRouteImport.update({
    id: '/holders',
    path: '/holders',
    getParentRoute: () => CollectionCollectionRoute,
  } as any)
const CollectionCollectionActivityRoute =
  CollectionCollectionActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => CollectionCollectionRoute,
  } as any)
const GameGamePlayerPlayerRoute = GameGamePlayerPlayerRouteImport.update({
  id: '/game/$game_/player/$player',
  path: '/game/$game/player/$player',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameCollectionCollectionRoute =
  GameGameCollectionCollectionRouteImport.update({
    id: '/collection/$collection',
    path: '/collection/$collection',
    getParentRoute: () => GameGameRoute,
  } as any)
const GameGamePlayerPlayerIndexRoute =
  GameGamePlayerPlayerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => GameGamePlayerPlayerRoute,
  } as any)
const GameGameEditionEditionIndexRoute =
  GameGameEditionEditionIndexRouteImport.update({
    id: '/edition/$edition/',
    path: '/edition/$edition/',
    getParentRoute: () => GameGameRoute,
  } as any)
const GameGameCollectionCollectionIndexRoute =
  GameGameCollectionCollectionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => GameGameCollectionCollectionRoute,
  } as any)
const GameGamePlayerPlayerPositionsRoute =
  GameGamePlayerPlayerPositionsRouteImport.update({
    id: '/positions',
    path: '/positions',
    getParentRoute: () => GameGamePlayerPlayerRoute,
  } as any)
const GameGamePlayerPlayerInventoryRoute =
  GameGamePlayerPlayerInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => GameGamePlayerPlayerRoute,
  } as any)
const GameGamePlayerPlayerActivityRoute =
  GameGamePlayerPlayerActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => GameGamePlayerPlayerRoute,
  } as any)
const GameGamePlayerPlayerAchievementsRoute =
  GameGamePlayerPlayerAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => GameGamePlayerPlayerRoute,
  } as any)
const GameGameEditionEditionPredictRoute =
  GameGameEditionEditionPredictRouteImport.update({
    id: '/edition/$edition/predict',
    path: '/edition/$edition/predict',
    getParentRoute: () => GameGameRoute,
  } as any)
const GameGameEditionEditionMarketplaceRoute =
  GameGameEditionEditionMarketplaceRouteImport.update({
    id: '/edition/$edition/marketplace',
    path: '/edition/$edition/marketplace',
    getParentRoute: () => GameGameRoute,
  } as any)
const GameGameEditionEditionLeaderboardRoute =
  GameGameEditionEditionLeaderboardRouteImport.update({
    id: '/edition/$edition/leaderboard',
    path: '/edition/$edition/leaderboard',
    getParentRoute: () => GameGameRoute,
  } as any)
const GameGameEditionEditionInventoryRoute =
  GameGameEditionEditionInventoryRouteImport.update({
    id: '/edition/$edition/inventory',
    path: '/edition/$edition/inventory',
    getParentRoute: () => GameGameRoute,
  } as any)
const GameGameEditionEditionGuildsRoute =
  GameGameEditionEditionGuildsRouteImport.update({
    id: '/edition/$edition/guilds',
    path: '/edition/$edition/guilds',
    getParentRoute: () => GameGameRoute,
  } as any)
const GameGameEditionEditionActivityRoute =
  GameGameEditionEditionActivityRouteImport.update({
    id: '/edition/$edition/activity',
    path: '/edition/$edition/activity',
    getParentRoute: () => GameGameRoute,
  } as any)
const GameGameEditionEditionAboutRoute =
  GameGameEditionEditionAboutRouteImport.update({
    id: '/edition/$edition/about',
    path: '/edition/$edition/about',
    getParentRoute: () => GameGameRoute,
  } as any)
const GameGameCollectionCollectionItemsRoute =
  GameGameCollectionCollectionItemsRouteImport.update({
    id: '/items',
    path: '/items',
    getParentRoute: () => GameGameCollectionCollectionRoute,
  } as any)
const GameGameCollectionCollectionHoldersRoute =
  GameGameCollectionCollectionHoldersRouteImport.update({
    id: '/holders',
    path: '/holders',
    getParentRoute: () => GameGameCollectionCollectionRoute,
  } as any)
const GameGameCollectionCollectionActivityRoute =
  GameGameCollectionCollectionActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => GameGameCollectionCollectionRoute,
  } as any)
const GameGameEditionEditionPlayerPlayerRoute =
  GameGameEditionEditionPlayerPlayerRouteImport.update({
    id: '/game/$game_/edition/$edition_/player/$player',
    path: '/game/$game/edition/$edition/player/$player',
    getParentRoute: () => rootRouteImport,
  } as any)
const GameGameEditionEditionCollectionCollectionRoute =
  GameGameEditionEditionCollectionCollectionRouteImport.update({
    id: '/game/$game_/edition/$edition_/collection/$collection',
    path: '/game/$game/edition/$edition/collection/$collection',
    getParentRoute: () => rootRouteImport,
  } as any)
const GameGameEditionEditionPlayerPlayerIndexRoute =
  GameGameEditionEditionPlayerPlayerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => GameGameEditionEditionPlayerPlayerRoute,
  } as any)
const GameGameEditionEditionCollectionCollectionIndexRoute =
  GameGameEditionEditionCollectionCollectionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => GameGameEditionEditionCollectionCollectionRoute,
  } as any)
const GameGameEditionEditionPlayerPlayerPositionsRoute =
  GameGameEditionEditionPlayerPlayerPositionsRouteImport.update({
    id: '/positions',
    path: '/positions',
    getParentRoute: () => GameGameEditionEditionPlayerPlayerRoute,
  } as any)
const GameGameEditionEditionPlayerPlayerInventoryRoute =
  GameGameEditionEditionPlayerPlayerInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => GameGameEditionEditionPlayerPlayerRoute,
  } as any)
const GameGameEditionEditionPlayerPlayerActivityRoute =
  GameGameEditionEditionPlayerPlayerActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => GameGameEditionEditionPlayerPlayerRoute,
  } as any)
const GameGameEditionEditionPlayerPlayerAchievementsRoute =
  GameGameEditionEditionPlayerPlayerAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => GameGameEditionEditionPlayerPlayerRoute,
  } as any)
const GameGameEditionEditionCollectionCollectionItemsRoute =
  GameGameEditionEditionCollectionCollectionItemsRouteImport.update({
    id: '/items',
    path: '/items',
    getParentRoute: () => GameGameEditionEditionCollectionCollectionRoute,
  } as any)
const GameGameEditionEditionCollectionCollectionHoldersRoute =
  GameGameEditionEditionCollectionCollectionHoldersRouteImport.update({
    id: '/holders',
    path: '/holders',
    getParentRoute: () => GameGameEditionEditionCollectionCollectionRoute,
  } as any)
const GameGameEditionEditionCollectionCollectionActivityRoute =
  GameGameEditionEditionCollectionCollectionActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => GameGameEditionEditionCollectionCollectionRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/guilds': typeof GuildsRoute
  '/inventory': typeof InventoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/marketplace': typeof MarketplaceRoute
  '/predict': typeof PredictRoute
  '/collection/$collection': typeof CollectionCollectionRouteWithChildren
  '/game/$game': typeof GameGameRouteWithChildren
  '/player/$player': typeof PlayerPlayerRouteWithChildren
  '/collection/$collection/activity': typeof CollectionCollectionActivityRoute
  '/collection/$collection/holders': typeof CollectionCollectionHoldersRoute
  '/collection/$collection/items': typeof CollectionCollectionItemsRoute
  '/game/$game/about': typeof GameGameAboutRoute
  '/game/$game/activity': typeof GameGameActivityRoute
  '/game/$game/guilds': typeof GameGameGuildsRoute
  '/game/$game/inventory': typeof GameGameInventoryRoute
  '/game/$game/leaderboard': typeof GameGameLeaderboardRoute
  '/game/$game/marketplace': typeof GameGameMarketplaceRoute
  '/game/$game/predict': typeof GameGamePredictRoute
  '/player/$player/achievements': typeof PlayerPlayerAchievementsRoute
  '/player/$player/activity': typeof PlayerPlayerActivityRoute
  '/player/$player/inventory': typeof PlayerPlayerInventoryRoute
  '/player/$player/positions': typeof PlayerPlayerPositionsRoute
  '/collection/$collection/': typeof CollectionCollectionIndexRoute
  '/game/$game/': typeof GameGameIndexRoute
  '/player/$player/': typeof PlayerPlayerIndexRoute
  '/game/$game/collection/$collection': typeof GameGameCollectionCollectionRouteWithChildren
  '/game/$game/player/$player': typeof GameGamePlayerPlayerRouteWithChildren
  '/game/$game/collection/$collection/activity': typeof GameGameCollectionCollectionActivityRoute
  '/game/$game/collection/$collection/holders': typeof GameGameCollectionCollectionHoldersRoute
  '/game/$game/collection/$collection/items': typeof GameGameCollectionCollectionItemsRoute
  '/game/$game/edition/$edition/about': typeof GameGameEditionEditionAboutRoute
  '/game/$game/edition/$edition/activity': typeof GameGameEditionEditionActivityRoute
  '/game/$game/edition/$edition/guilds': typeof GameGameEditionEditionGuildsRoute
  '/game/$game/edition/$edition/inventory': typeof GameGameEditionEditionInventoryRoute
  '/game/$game/edition/$edition/leaderboard': typeof GameGameEditionEditionLeaderboardRoute
  '/game/$game/edition/$edition/marketplace': typeof GameGameEditionEditionMarketplaceRoute
  '/game/$game/edition/$edition/predict': typeof GameGameEditionEditionPredictRoute
  '/game/$game/player/$player/achievements': typeof GameGamePlayerPlayerAchievementsRoute
  '/game/$game/player/$player/activity': typeof GameGamePlayerPlayerActivityRoute
  '/game/$game/player/$player/inventory': typeof GameGamePlayerPlayerInventoryRoute
  '/game/$game/player/$player/positions': typeof GameGamePlayerPlayerPositionsRoute
  '/game/$game/collection/$collection/': typeof GameGameCollectionCollectionIndexRoute
  '/game/$game/edition/$edition': typeof GameGameEditionEditionIndexRoute
  '/game/$game/player/$player/': typeof GameGamePlayerPlayerIndexRoute
  '/game/$game/edition/$edition/collection/$collection': typeof GameGameEditionEditionCollectionCollectionRouteWithChildren
  '/game/$game/edition/$edition/player/$player': typeof GameGameEditionEditionPlayerPlayerRouteWithChildren
  '/game/$game/edition/$edition/collection/$collection/activity': typeof GameGameEditionEditionCollectionCollectionActivityRoute
  '/game/$game/edition/$edition/collection/$collection/holders': typeof GameGameEditionEditionCollectionCollectionHoldersRoute
  '/game/$game/edition/$edition/collection/$collection/items': typeof GameGameEditionEditionCollectionCollectionItemsRoute
  '/game/$game/edition/$edition/player/$player/achievements': typeof GameGameEditionEditionPlayerPlayerAchievementsRoute
  '/game/$game/edition/$edition/player/$player/activity': typeof GameGameEditionEditionPlayerPlayerActivityRoute
  '/game/$game/edition/$edition/player/$player/inventory': typeof GameGameEditionEditionPlayerPlayerInventoryRoute
  '/game/$game/edition/$edition/player/$player/positions': typeof GameGameEditionEditionPlayerPlayerPositionsRoute
  '/game/$game/edition/$edition/collection/$collection/': typeof GameGameEditionEditionCollectionCollectionIndexRoute
  '/game/$game/edition/$edition/player/$player/': typeof GameGameEditionEditionPlayerPlayerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/guilds': typeof GuildsRoute
  '/inventory': typeof InventoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/marketplace': typeof MarketplaceRoute
  '/predict': typeof PredictRoute
  '/collection/$collection/activity': typeof CollectionCollectionActivityRoute
  '/collection/$collection/holders': typeof CollectionCollectionHoldersRoute
  '/collection/$collection/items': typeof CollectionCollectionItemsRoute
  '/game/$game/about': typeof GameGameAboutRoute
  '/game/$game/activity': typeof GameGameActivityRoute
  '/game/$game/guilds': typeof GameGameGuildsRoute
  '/game/$game/inventory': typeof GameGameInventoryRoute
  '/game/$game/leaderboard': typeof GameGameLeaderboardRoute
  '/game/$game/marketplace': typeof GameGameMarketplaceRoute
  '/game/$game/predict': typeof GameGamePredictRoute
  '/player/$player/achievements': typeof PlayerPlayerAchievementsRoute
  '/player/$player/activity': typeof PlayerPlayerActivityRoute
  '/player/$player/inventory': typeof PlayerPlayerInventoryRoute
  '/player/$player/positions': typeof PlayerPlayerPositionsRoute
  '/collection/$collection': typeof CollectionCollectionIndexRoute
  '/game/$game': typeof GameGameIndexRoute
  '/player/$player': typeof PlayerPlayerIndexRoute
  '/game/$game/collection/$collection/activity': typeof GameGameCollectionCollectionActivityRoute
  '/game/$game/collection/$collection/holders': typeof GameGameCollectionCollectionHoldersRoute
  '/game/$game/collection/$collection/items': typeof GameGameCollectionCollectionItemsRoute
  '/game/$game/edition/$edition/about': typeof GameGameEditionEditionAboutRoute
  '/game/$game/edition/$edition/activity': typeof GameGameEditionEditionActivityRoute
  '/game/$game/edition/$edition/guilds': typeof GameGameEditionEditionGuildsRoute
  '/game/$game/edition/$edition/inventory': typeof GameGameEditionEditionInventoryRoute
  '/game/$game/edition/$edition/leaderboard': typeof GameGameEditionEditionLeaderboardRoute
  '/game/$game/edition/$edition/marketplace': typeof GameGameEditionEditionMarketplaceRoute
  '/game/$game/edition/$edition/predict': typeof GameGameEditionEditionPredictRoute
  '/game/$game/player/$player/achievements': typeof GameGamePlayerPlayerAchievementsRoute
  '/game/$game/player/$player/activity': typeof GameGamePlayerPlayerActivityRoute
  '/game/$game/player/$player/inventory': typeof GameGamePlayerPlayerInventoryRoute
  '/game/$game/player/$player/positions': typeof GameGamePlayerPlayerPositionsRoute
  '/game/$game/collection/$collection': typeof GameGameCollectionCollectionIndexRoute
  '/game/$game/edition/$edition': typeof GameGameEditionEditionIndexRoute
  '/game/$game/player/$player': typeof GameGamePlayerPlayerIndexRoute
  '/game/$game/edition/$edition/collection/$collection/activity': typeof GameGameEditionEditionCollectionCollectionActivityRoute
  '/game/$game/edition/$edition/collection/$collection/holders': typeof GameGameEditionEditionCollectionCollectionHoldersRoute
  '/game/$game/edition/$edition/collection/$collection/items': typeof GameGameEditionEditionCollectionCollectionItemsRoute
  '/game/$game/edition/$edition/player/$player/achievements': typeof GameGameEditionEditionPlayerPlayerAchievementsRoute
  '/game/$game/edition/$edition/player/$player/activity': typeof GameGameEditionEditionPlayerPlayerActivityRoute
  '/game/$game/edition/$edition/player/$player/inventory': typeof GameGameEditionEditionPlayerPlayerInventoryRoute
  '/game/$game/edition/$edition/player/$player/positions': typeof GameGameEditionEditionPlayerPlayerPositionsRoute
  '/game/$game/edition/$edition/collection/$collection': typeof GameGameEditionEditionCollectionCollectionIndexRoute
  '/game/$game/edition/$edition/player/$player': typeof GameGameEditionEditionPlayerPlayerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/guilds': typeof GuildsRoute
  '/inventory': typeof InventoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/marketplace': typeof MarketplaceRoute
  '/predict': typeof PredictRoute
  '/collection/$collection': typeof CollectionCollectionRouteWithChildren
  '/game/$game': typeof GameGameRouteWithChildren
  '/player/$player': typeof PlayerPlayerRouteWithChildren
  '/collection/$collection/activity': typeof CollectionCollectionActivityRoute
  '/collection/$collection/holders': typeof CollectionCollectionHoldersRoute
  '/collection/$collection/items': typeof CollectionCollectionItemsRoute
  '/game/$game/about': typeof GameGameAboutRoute
  '/game/$game/activity': typeof GameGameActivityRoute
  '/game/$game/guilds': typeof GameGameGuildsRoute
  '/game/$game/inventory': typeof GameGameInventoryRoute
  '/game/$game/leaderboard': typeof GameGameLeaderboardRoute
  '/game/$game/marketplace': typeof GameGameMarketplaceRoute
  '/game/$game/predict': typeof GameGamePredictRoute
  '/player/$player/achievements': typeof PlayerPlayerAchievementsRoute
  '/player/$player/activity': typeof PlayerPlayerActivityRoute
  '/player/$player/inventory': typeof PlayerPlayerInventoryRoute
  '/player/$player/positions': typeof PlayerPlayerPositionsRoute
  '/collection/$collection/': typeof CollectionCollectionIndexRoute
  '/game/$game/': typeof GameGameIndexRoute
  '/player/$player/': typeof PlayerPlayerIndexRoute
  '/game/$game/collection/$collection': typeof GameGameCollectionCollectionRouteWithChildren
  '/game/$game_/player/$player': typeof GameGamePlayerPlayerRouteWithChildren
  '/game/$game/collection/$collection/activity': typeof GameGameCollectionCollectionActivityRoute
  '/game/$game/collection/$collection/holders': typeof GameGameCollectionCollectionHoldersRoute
  '/game/$game/collection/$collection/items': typeof GameGameCollectionCollectionItemsRoute
  '/game/$game/edition/$edition/about': typeof GameGameEditionEditionAboutRoute
  '/game/$game/edition/$edition/activity': typeof GameGameEditionEditionActivityRoute
  '/game/$game/edition/$edition/guilds': typeof GameGameEditionEditionGuildsRoute
  '/game/$game/edition/$edition/inventory': typeof GameGameEditionEditionInventoryRoute
  '/game/$game/edition/$edition/leaderboard': typeof GameGameEditionEditionLeaderboardRoute
  '/game/$game/edition/$edition/marketplace': typeof GameGameEditionEditionMarketplaceRoute
  '/game/$game/edition/$edition/predict': typeof GameGameEditionEditionPredictRoute
  '/game/$game_/player/$player/achievements': typeof GameGamePlayerPlayerAchievementsRoute
  '/game/$game_/player/$player/activity': typeof GameGamePlayerPlayerActivityRoute
  '/game/$game_/player/$player/inventory': typeof GameGamePlayerPlayerInventoryRoute
  '/game/$game_/player/$player/positions': typeof GameGamePlayerPlayerPositionsRoute
  '/game/$game/collection/$collection/': typeof GameGameCollectionCollectionIndexRoute
  '/game/$game/edition/$edition/': typeof GameGameEditionEditionIndexRoute
  '/game/$game_/player/$player/': typeof GameGamePlayerPlayerIndexRoute
  '/game/$game_/edition/$edition_/collection/$collection': typeof GameGameEditionEditionCollectionCollectionRouteWithChildren
  '/game/$game_/edition/$edition_/player/$player': typeof GameGameEditionEditionPlayerPlayerRouteWithChildren
  '/game/$game_/edition/$edition_/collection/$collection/activity': typeof GameGameEditionEditionCollectionCollectionActivityRoute
  '/game/$game_/edition/$edition_/collection/$collection/holders': typeof GameGameEditionEditionCollectionCollectionHoldersRoute
  '/game/$game_/edition/$edition_/collection/$collection/items': typeof GameGameEditionEditionCollectionCollectionItemsRoute
  '/game/$game_/edition/$edition_/player/$player/achievements': typeof GameGameEditionEditionPlayerPlayerAchievementsRoute
  '/game/$game_/edition/$edition_/player/$player/activity': typeof GameGameEditionEditionPlayerPlayerActivityRoute
  '/game/$game_/edition/$edition_/player/$player/inventory': typeof GameGameEditionEditionPlayerPlayerInventoryRoute
  '/game/$game_/edition/$edition_/player/$player/positions': typeof GameGameEditionEditionPlayerPlayerPositionsRoute
  '/game/$game_/edition/$edition_/collection/$collection/': typeof GameGameEditionEditionCollectionCollectionIndexRoute
  '/game/$game_/edition/$edition_/player/$player/': typeof GameGameEditionEditionPlayerPlayerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/guilds'
    | '/inventory'
    | '/leaderboard'
    | '/marketplace'
    | '/predict'
    | '/collection/$collection'
    | '/game/$game'
    | '/player/$player'
    | '/collection/$collection/activity'
    | '/collection/$collection/holders'
    | '/collection/$collection/items'
    | '/game/$game/about'
    | '/game/$game/activity'
    | '/game/$game/guilds'
    | '/game/$game/inventory'
    | '/game/$game/leaderboard'
    | '/game/$game/marketplace'
    | '/game/$game/predict'
    | '/player/$player/achievements'
    | '/player/$player/activity'
    | '/player/$player/inventory'
    | '/player/$player/positions'
    | '/collection/$collection/'
    | '/game/$game/'
    | '/player/$player/'
    | '/game/$game/collection/$collection'
    | '/game/$game/player/$player'
    | '/game/$game/collection/$collection/activity'
    | '/game/$game/collection/$collection/holders'
    | '/game/$game/collection/$collection/items'
    | '/game/$game/edition/$edition/about'
    | '/game/$game/edition/$edition/activity'
    | '/game/$game/edition/$edition/guilds'
    | '/game/$game/edition/$edition/inventory'
    | '/game/$game/edition/$edition/leaderboard'
    | '/game/$game/edition/$edition/marketplace'
    | '/game/$game/edition/$edition/predict'
    | '/game/$game/player/$player/achievements'
    | '/game/$game/player/$player/activity'
    | '/game/$game/player/$player/inventory'
    | '/game/$game/player/$player/positions'
    | '/game/$game/collection/$collection/'
    | '/game/$game/edition/$edition'
    | '/game/$game/player/$player/'
    | '/game/$game/edition/$edition/collection/$collection'
    | '/game/$game/edition/$edition/player/$player'
    | '/game/$game/edition/$edition/collection/$collection/activity'
    | '/game/$game/edition/$edition/collection/$collection/holders'
    | '/game/$game/edition/$edition/collection/$collection/items'
    | '/game/$game/edition/$edition/player/$player/achievements'
    | '/game/$game/edition/$edition/player/$player/activity'
    | '/game/$game/edition/$edition/player/$player/inventory'
    | '/game/$game/edition/$edition/player/$player/positions'
    | '/game/$game/edition/$edition/collection/$collection/'
    | '/game/$game/edition/$edition/player/$player/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/guilds'
    | '/inventory'
    | '/leaderboard'
    | '/marketplace'
    | '/predict'
    | '/collection/$collection/activity'
    | '/collection/$collection/holders'
    | '/collection/$collection/items'
    | '/game/$game/about'
    | '/game/$game/activity'
    | '/game/$game/guilds'
    | '/game/$game/inventory'
    | '/game/$game/leaderboard'
    | '/game/$game/marketplace'
    | '/game/$game/predict'
    | '/player/$player/achievements'
    | '/player/$player/activity'
    | '/player/$player/inventory'
    | '/player/$player/positions'
    | '/collection/$collection'
    | '/game/$game'
    | '/player/$player'
    | '/game/$game/collection/$collection/activity'
    | '/game/$game/collection/$collection/holders'
    | '/game/$game/collection/$collection/items'
    | '/game/$game/edition/$edition/about'
    | '/game/$game/edition/$edition/activity'
    | '/game/$game/edition/$edition/guilds'
    | '/game/$game/edition/$edition/inventory'
    | '/game/$game/edition/$edition/leaderboard'
    | '/game/$game/edition/$edition/marketplace'
    | '/game/$game/edition/$edition/predict'
    | '/game/$game/player/$player/achievements'
    | '/game/$game/player/$player/activity'
    | '/game/$game/player/$player/inventory'
    | '/game/$game/player/$player/positions'
    | '/game/$game/collection/$collection'
    | '/game/$game/edition/$edition'
    | '/game/$game/player/$player'
    | '/game/$game/edition/$edition/collection/$collection/activity'
    | '/game/$game/edition/$edition/collection/$collection/holders'
    | '/game/$game/edition/$edition/collection/$collection/items'
    | '/game/$game/edition/$edition/player/$player/achievements'
    | '/game/$game/edition/$edition/player/$player/activity'
    | '/game/$game/edition/$edition/player/$player/inventory'
    | '/game/$game/edition/$edition/player/$player/positions'
    | '/game/$game/edition/$edition/collection/$collection'
    | '/game/$game/edition/$edition/player/$player'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/guilds'
    | '/inventory'
    | '/leaderboard'
    | '/marketplace'
    | '/predict'
    | '/collection/$collection'
    | '/game/$game'
    | '/player/$player'
    | '/collection/$collection/activity'
    | '/collection/$collection/holders'
    | '/collection/$collection/items'
    | '/game/$game/about'
    | '/game/$game/activity'
    | '/game/$game/guilds'
    | '/game/$game/inventory'
    | '/game/$game/leaderboard'
    | '/game/$game/marketplace'
    | '/game/$game/predict'
    | '/player/$player/achievements'
    | '/player/$player/activity'
    | '/player/$player/inventory'
    | '/player/$player/positions'
    | '/collection/$collection/'
    | '/game/$game/'
    | '/player/$player/'
    | '/game/$game/collection/$collection'
    | '/game/$game_/player/$player'
    | '/game/$game/collection/$collection/activity'
    | '/game/$game/collection/$collection/holders'
    | '/game/$game/collection/$collection/items'
    | '/game/$game/edition/$edition/about'
    | '/game/$game/edition/$edition/activity'
    | '/game/$game/edition/$edition/guilds'
    | '/game/$game/edition/$edition/inventory'
    | '/game/$game/edition/$edition/leaderboard'
    | '/game/$game/edition/$edition/marketplace'
    | '/game/$game/edition/$edition/predict'
    | '/game/$game_/player/$player/achievements'
    | '/game/$game_/player/$player/activity'
    | '/game/$game_/player/$player/inventory'
    | '/game/$game_/player/$player/positions'
    | '/game/$game/collection/$collection/'
    | '/game/$game/edition/$edition/'
    | '/game/$game_/player/$player/'
    | '/game/$game_/edition/$edition_/collection/$collection'
    | '/game/$game_/edition/$edition_/player/$player'
    | '/game/$game_/edition/$edition_/collection/$collection/activity'
    | '/game/$game_/edition/$edition_/collection/$collection/holders'
    | '/game/$game_/edition/$edition_/collection/$collection/items'
    | '/game/$game_/edition/$edition_/player/$player/achievements'
    | '/game/$game_/edition/$edition_/player/$player/activity'
    | '/game/$game_/edition/$edition_/player/$player/inventory'
    | '/game/$game_/edition/$edition_/player/$player/positions'
    | '/game/$game_/edition/$edition_/collection/$collection/'
    | '/game/$game_/edition/$edition_/player/$player/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GuildsRoute: typeof GuildsRoute
  InventoryRoute: typeof InventoryRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MarketplaceRoute: typeof MarketplaceRoute
  PredictRoute: typeof PredictRoute
  CollectionCollectionRoute: typeof CollectionCollectionRouteWithChildren
  GameGameRoute: typeof GameGameRouteWithChildren
  PlayerPlayerRoute: typeof PlayerPlayerRouteWithChildren
  GameGamePlayerPlayerRoute: typeof GameGamePlayerPlayerRouteWithChildren
  GameGameEditionEditionCollectionCollectionRoute: typeof GameGameEditionEditionCollectionCollectionRouteWithChildren
  GameGameEditionEditionPlayerPlayerRoute: typeof GameGameEditionEditionPlayerPlayerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/predict': {
      id: '/predict'
      path: '/predict'
      fullPath: '/predict'
      preLoaderRoute: typeof PredictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guilds': {
      id: '/guilds'
      path: '/guilds'
      fullPath: '/guilds'
      preLoaderRoute: typeof GuildsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$player': {
      id: '/player/$player'
      path: '/player/$player'
      fullPath: '/player/$player'
      preLoaderRoute: typeof PlayerPlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$game': {
      id: '/game/$game'
      path: '/game/$game'
      fullPath: '/game/$game'
      preLoaderRoute: typeof GameGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/$collection': {
      id: '/collection/$collection'
      path: '/collection/$collection'
      fullPath: '/collection/$collection'
      preLoaderRoute: typeof CollectionCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$player/': {
      id: '/player/$player/'
      path: '/'
      fullPath: '/player/$player/'
      preLoaderRoute: typeof PlayerPlayerIndexRouteImport
      parentRoute: typeof PlayerPlayerRoute
    }
    '/game/$game/': {
      id: '/game/$game/'
      path: '/'
      fullPath: '/game/$game/'
      preLoaderRoute: typeof GameGameIndexRouteImport
      parentRoute: typeof GameGameRoute
    }
    '/collection/$collection/': {
      id: '/collection/$collection/'
      path: '/'
      fullPath: '/collection/$collection/'
      preLoaderRoute: typeof CollectionCollectionIndexRouteImport
      parentRoute: typeof CollectionCollectionRoute
    }
    '/player/$player/positions': {
      id: '/player/$player/positions'
      path: '/positions'
      fullPath: '/player/$player/positions'
      preLoaderRoute: typeof PlayerPlayerPositionsRouteImport
      parentRoute: typeof PlayerPlayerRoute
    }
    '/player/$player/inventory': {
      id: '/player/$player/inventory'
      path: '/inventory'
      fullPath: '/player/$player/inventory'
      preLoaderRoute: typeof PlayerPlayerInventoryRouteImport
      parentRoute: typeof PlayerPlayerRoute
    }
    '/player/$player/activity': {
      id: '/player/$player/activity'
      path: '/activity'
      fullPath: '/player/$player/activity'
      preLoaderRoute: typeof PlayerPlayerActivityRouteImport
      parentRoute: typeof PlayerPlayerRoute
    }
    '/player/$player/achievements': {
      id: '/player/$player/achievements'
      path: '/achievements'
      fullPath: '/player/$player/achievements'
      preLoaderRoute: typeof PlayerPlayerAchievementsRouteImport
      parentRoute: typeof PlayerPlayerRoute
    }
    '/game/$game/predict': {
      id: '/game/$game/predict'
      path: '/predict'
      fullPath: '/game/$game/predict'
      preLoaderRoute: typeof GameGamePredictRouteImport
      parentRoute: typeof GameGameRoute
    }
    '/game/$game/marketplace': {
      id: '/game/$game/marketplace'
      path: '/marketplace'
      fullPath: '/game/$game/marketplace'
      preLoaderRoute: typeof GameGameMarketplaceRouteImport
      parentRoute: typeof GameGameRoute
    }
    '/game/$game/leaderboard': {
      id: '/game/$game/leaderboard'
      path: '/leaderboard'
      fullPath: '/game/$game/leaderboard'
      preLoaderRoute: typeof GameGameLeaderboardRouteImport
      parentRoute: typeof GameGameRoute
    }
    '/game/$game/inventory': {
      id: '/game/$game/inventory'
      path: '/inventory'
      fullPath: '/game/$game/inventory'
      preLoaderRoute: typeof GameGameInventoryRouteImport
      parentRoute: typeof GameGameRoute
    }
    '/game/$game/guilds': {
      id: '/game/$game/guilds'
      path: '/guilds'
      fullPath: '/game/$game/guilds'
      preLoaderRoute: typeof GameGameGuildsRouteImport
      parentRoute: typeof GameGameRoute
    }
    '/game/$game/activity': {
      id: '/game/$game/activity'
      path: '/activity'
      fullPath: '/game/$game/activity'
      preLoaderRoute: typeof GameGameActivityRouteImport
      parentRoute: typeof GameGameRoute
    }
    '/game/$game/about': {
      id: '/game/$game/about'
      path: '/about'
      fullPath: '/game/$game/about'
      preLoaderRoute: typeof GameGameAboutRouteImport
      parentRoute: typeof GameGameRoute
    }
    '/collection/$collection/items': {
      id: '/collection/$collection/items'
      path: '/items'
      fullPath: '/collection/$collection/items'
      preLoaderRoute: typeof CollectionCollectionItemsRouteImport
      parentRoute: typeof CollectionCollectionRoute
    }
    '/collection/$collection/holders': {
      id: '/collection/$collection/holders'
      path: '/holders'
      fullPath: '/collection/$collection/holders'
      preLoaderRoute: typeof CollectionCollectionHoldersRouteImport
      parentRoute: typeof CollectionCollectionRoute
    }
    '/collection/$collection/activity': {
      id: '/collection/$collection/activity'
      path: '/activity'
      fullPath: '/collection/$collection/activity'
      preLoaderRoute: typeof CollectionCollectionActivityRouteImport
      parentRoute: typeof CollectionCollectionRoute
    }
    '/game/$game_/player/$player': {
      id: '/game/$game_/player/$player'
      path: '/game/$game/player/$player'
      fullPath: '/game/$game/player/$player'
      preLoaderRoute: typeof GameGamePlayerPlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$game/collection/$collection': {
      id: '/game/$game/collection/$collection'
      path: '/collection/$collection'
      fullPath: '/game/$game/collection/$collection'
      preLoaderRoute: typeof GameGameCollectionCollectionRouteImport
      parentRoute: typeof GameGameRoute
    }
    '/game/$game_/player/$player/': {
      id: '/game/$game_/player/$player/'
      path: '/'
      fullPath: '/game/$game/player/$player/'
      preLoaderRoute: typeof GameGamePlayerPlayerIndexRouteImport
      parentRoute: typeof GameGamePlayerPlayerRoute
    }
    '/game/$game/edition/$edition/': {
      id: '/game/$game/edition/$edition/'
      path: '/edition/$edition'
      fullPath: '/game/$game/edition/$edition'
      preLoaderRoute: typeof GameGameEditionEditionIndexRouteImport
      parentRoute: typeof GameGameRoute
    }
    '/game/$game/collection/$collection/': {
      id: '/game/$game/collection/$collection/'
      path: '/'
      fullPath: '/game/$game/collection/$collection/'
      preLoaderRoute: typeof GameGameCollectionCollectionIndexRouteImport
      parentRoute: typeof GameGameCollectionCollectionRoute
    }
    '/game/$game_/player/$player/positions': {
      id: '/game/$game_/player/$player/positions'
      path: '/positions'
      fullPath: '/game/$game/player/$player/positions'
      preLoaderRoute: typeof GameGamePlayerPlayerPositionsRouteImport
      parentRoute: typeof GameGamePlayerPlayerRoute
    }
    '/game/$game_/player/$player/inventory': {
      id: '/game/$game_/player/$player/inventory'
      path: '/inventory'
      fullPath: '/game/$game/player/$player/inventory'
      preLoaderRoute: typeof GameGamePlayerPlayerInventoryRouteImport
      parentRoute: typeof GameGamePlayerPlayerRoute
    }
    '/game/$game_/player/$player/activity': {
      id: '/game/$game_/player/$player/activity'
      path: '/activity'
      fullPath: '/game/$game/player/$player/activity'
      preLoaderRoute: typeof GameGamePlayerPlayerActivityRouteImport
      parentRoute: typeof GameGamePlayerPlayerRoute
    }
    '/game/$game_/player/$player/achievements': {
      id: '/game/$game_/player/$player/achievements'
      path: '/achievements'
      fullPath: '/game/$game/player/$player/achievements'
      preLoaderRoute: typeof GameGamePlayerPlayerAchievementsRouteImport
      parentRoute: typeof GameGamePlayerPlayerRoute
    }
    '/game/$game/edition/$edition/predict': {
      id: '/game/$game/edition/$edition/predict'
      path: '/edition/$edition/predict'
      fullPath: '/game/$game/edition/$edition/predict'
      preLoaderRoute: typeof GameGameEditionEditionPredictRouteImport
      parentRoute: typeof GameGameRoute
    }
    '/game/$game/edition/$edition/marketplace': {
      id: '/game/$game/edition/$edition/marketplace'
      path: '/edition/$edition/marketplace'
      fullPath: '/game/$game/edition/$edition/marketplace'
      preLoaderRoute: typeof GameGameEditionEditionMarketplaceRouteImport
      parentRoute: typeof GameGameRoute
    }
    '/game/$game/edition/$edition/leaderboard': {
      id: '/game/$game/edition/$edition/leaderboard'
      path: '/edition/$edition/leaderboard'
      fullPath: '/game/$game/edition/$edition/leaderboard'
      preLoaderRoute: typeof GameGameEditionEditionLeaderboardRouteImport
      parentRoute: typeof GameGameRoute
    }
    '/game/$game/edition/$edition/inventory': {
      id: '/game/$game/edition/$edition/inventory'
      path: '/edition/$edition/inventory'
      fullPath: '/game/$game/edition/$edition/inventory'
      preLoaderRoute: typeof GameGameEditionEditionInventoryRouteImport
      parentRoute: typeof GameGameRoute
    }
    '/game/$game/edition/$edition/guilds': {
      id: '/game/$game/edition/$edition/guilds'
      path: '/edition/$edition/guilds'
      fullPath: '/game/$game/edition/$edition/guilds'
      preLoaderRoute: typeof GameGameEditionEditionGuildsRouteImport
      parentRoute: typeof GameGameRoute
    }
    '/game/$game/edition/$edition/activity': {
      id: '/game/$game/edition/$edition/activity'
      path: '/edition/$edition/activity'
      fullPath: '/game/$game/edition/$edition/activity'
      preLoaderRoute: typeof GameGameEditionEditionActivityRouteImport
      parentRoute: typeof GameGameRoute
    }
    '/game/$game/edition/$edition/about': {
      id: '/game/$game/edition/$edition/about'
      path: '/edition/$edition/about'
      fullPath: '/game/$game/edition/$edition/about'
      preLoaderRoute: typeof GameGameEditionEditionAboutRouteImport
      parentRoute: typeof GameGameRoute
    }
    '/game/$game/collection/$collection/items': {
      id: '/game/$game/collection/$collection/items'
      path: '/items'
      fullPath: '/game/$game/collection/$collection/items'
      preLoaderRoute: typeof GameGameCollectionCollectionItemsRouteImport
      parentRoute: typeof GameGameCollectionCollectionRoute
    }
    '/game/$game/collection/$collection/holders': {
      id: '/game/$game/collection/$collection/holders'
      path: '/holders'
      fullPath: '/game/$game/collection/$collection/holders'
      preLoaderRoute: typeof GameGameCollectionCollectionHoldersRouteImport
      parentRoute: typeof GameGameCollectionCollectionRoute
    }
    '/game/$game/collection/$collection/activity': {
      id: '/game/$game/collection/$collection/activity'
      path: '/activity'
      fullPath: '/game/$game/collection/$collection/activity'
      preLoaderRoute: typeof GameGameCollectionCollectionActivityRouteImport
      parentRoute: typeof GameGameCollectionCollectionRoute
    }
    '/game/$game_/edition/$edition_/player/$player': {
      id: '/game/$game_/edition/$edition_/player/$player'
      path: '/game/$game/edition/$edition/player/$player'
      fullPath: '/game/$game/edition/$edition/player/$player'
      preLoaderRoute: typeof GameGameEditionEditionPlayerPlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$game_/edition/$edition_/collection/$collection': {
      id: '/game/$game_/edition/$edition_/collection/$collection'
      path: '/game/$game/edition/$edition/collection/$collection'
      fullPath: '/game/$game/edition/$edition/collection/$collection'
      preLoaderRoute: typeof GameGameEditionEditionCollectionCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$game_/edition/$edition_/player/$player/': {
      id: '/game/$game_/edition/$edition_/player/$player/'
      path: '/'
      fullPath: '/game/$game/edition/$edition/player/$player/'
      preLoaderRoute: typeof GameGameEditionEditionPlayerPlayerIndexRouteImport
      parentRoute: typeof GameGameEditionEditionPlayerPlayerRoute
    }
    '/game/$game_/edition/$edition_/collection/$collection/': {
      id: '/game/$game_/edition/$edition_/collection/$collection/'
      path: '/'
      fullPath: '/game/$game/edition/$edition/collection/$collection/'
      preLoaderRoute: typeof GameGameEditionEditionCollectionCollectionIndexRouteImport
      parentRoute: typeof GameGameEditionEditionCollectionCollectionRoute
    }
    '/game/$game_/edition/$edition_/player/$player/positions': {
      id: '/game/$game_/edition/$edition_/player/$player/positions'
      path: '/positions'
      fullPath: '/game/$game/edition/$edition/player/$player/positions'
      preLoaderRoute: typeof GameGameEditionEditionPlayerPlayerPositionsRouteImport
      parentRoute: typeof GameGameEditionEditionPlayerPlayerRoute
    }
    '/game/$game_/edition/$edition_/player/$player/inventory': {
      id: '/game/$game_/edition/$edition_/player/$player/inventory'
      path: '/inventory'
      fullPath: '/game/$game/edition/$edition/player/$player/inventory'
      preLoaderRoute: typeof GameGameEditionEditionPlayerPlayerInventoryRouteImport
      parentRoute: typeof GameGameEditionEditionPlayerPlayerRoute
    }
    '/game/$game_/edition/$edition_/player/$player/activity': {
      id: '/game/$game_/edition/$edition_/player/$player/activity'
      path: '/activity'
      fullPath: '/game/$game/edition/$edition/player/$player/activity'
      preLoaderRoute: typeof GameGameEditionEditionPlayerPlayerActivityRouteImport
      parentRoute: typeof GameGameEditionEditionPlayerPlayerRoute
    }
    '/game/$game_/edition/$edition_/player/$player/achievements': {
      id: '/game/$game_/edition/$edition_/player/$player/achievements'
      path: '/achievements'
      fullPath: '/game/$game/edition/$edition/player/$player/achievements'
      preLoaderRoute: typeof GameGameEditionEditionPlayerPlayerAchievementsRouteImport
      parentRoute: typeof GameGameEditionEditionPlayerPlayerRoute
    }
    '/game/$game_/edition/$edition_/collection/$collection/items': {
      id: '/game/$game_/edition/$edition_/collection/$collection/items'
      path: '/items'
      fullPath: '/game/$game/edition/$edition/collection/$collection/items'
      preLoaderRoute: typeof GameGameEditionEditionCollectionCollectionItemsRouteImport
      parentRoute: typeof GameGameEditionEditionCollectionCollectionRoute
    }
    '/game/$game_/edition/$edition_/collection/$collection/holders': {
      id: '/game/$game_/edition/$edition_/collection/$collection/holders'
      path: '/holders'
      fullPath: '/game/$game/edition/$edition/collection/$collection/holders'
      preLoaderRoute: typeof GameGameEditionEditionCollectionCollectionHoldersRouteImport
      parentRoute: typeof GameGameEditionEditionCollectionCollectionRoute
    }
    '/game/$game_/edition/$edition_/collection/$collection/activity': {
      id: '/game/$game_/edition/$edition_/collection/$collection/activity'
      path: '/activity'
      fullPath: '/game/$game/edition/$edition/collection/$collection/activity'
      preLoaderRoute: typeof GameGameEditionEditionCollectionCollectionActivityRouteImport
      parentRoute: typeof GameGameEditionEditionCollectionCollectionRoute
    }
  }
}

interface CollectionCollectionRouteChildren {
  CollectionCollectionActivityRoute: typeof CollectionCollectionActivityRoute
  CollectionCollectionHoldersRoute: typeof CollectionCollectionHoldersRoute
  CollectionCollectionItemsRoute: typeof CollectionCollectionItemsRoute
  CollectionCollectionIndexRoute: typeof CollectionCollectionIndexRoute
}

const CollectionCollectionRouteChildren: CollectionCollectionRouteChildren = {
  CollectionCollectionActivityRoute: CollectionCollectionActivityRoute,
  CollectionCollectionHoldersRoute: CollectionCollectionHoldersRoute,
  CollectionCollectionItemsRoute: CollectionCollectionItemsRoute,
  CollectionCollectionIndexRoute: CollectionCollectionIndexRoute,
}

const CollectionCollectionRouteWithChildren =
  CollectionCollectionRoute._addFileChildren(CollectionCollectionRouteChildren)

interface GameGameCollectionCollectionRouteChildren {
  GameGameCollectionCollectionActivityRoute: typeof GameGameCollectionCollectionActivityRoute
  GameGameCollectionCollectionHoldersRoute: typeof GameGameCollectionCollectionHoldersRoute
  GameGameCollectionCollectionItemsRoute: typeof GameGameCollectionCollectionItemsRoute
  GameGameCollectionCollectionIndexRoute: typeof GameGameCollectionCollectionIndexRoute
}

const GameGameCollectionCollectionRouteChildren: GameGameCollectionCollectionRouteChildren =
  {
    GameGameCollectionCollectionActivityRoute:
      GameGameCollectionCollectionActivityRoute,
    GameGameCollectionCollectionHoldersRoute:
      GameGameCollectionCollectionHoldersRoute,
    GameGameCollectionCollectionItemsRoute:
      GameGameCollectionCollectionItemsRoute,
    GameGameCollectionCollectionIndexRoute:
      GameGameCollectionCollectionIndexRoute,
  }

const GameGameCollectionCollectionRouteWithChildren =
  GameGameCollectionCollectionRoute._addFileChildren(
    GameGameCollectionCollectionRouteChildren,
  )

interface GameGameRouteChildren {
  GameGameAboutRoute: typeof GameGameAboutRoute
  GameGameActivityRoute: typeof GameGameActivityRoute
  GameGameGuildsRoute: typeof GameGameGuildsRoute
  GameGameInventoryRoute: typeof GameGameInventoryRoute
  GameGameLeaderboardRoute: typeof GameGameLeaderboardRoute
  GameGameMarketplaceRoute: typeof GameGameMarketplaceRoute
  GameGamePredictRoute: typeof GameGamePredictRoute
  GameGameIndexRoute: typeof GameGameIndexRoute
  GameGameCollectionCollectionRoute: typeof GameGameCollectionCollectionRouteWithChildren
  GameGameEditionEditionAboutRoute: typeof GameGameEditionEditionAboutRoute
  GameGameEditionEditionActivityRoute: typeof GameGameEditionEditionActivityRoute
  GameGameEditionEditionGuildsRoute: typeof GameGameEditionEditionGuildsRoute
  GameGameEditionEditionInventoryRoute: typeof GameGameEditionEditionInventoryRoute
  GameGameEditionEditionLeaderboardRoute: typeof GameGameEditionEditionLeaderboardRoute
  GameGameEditionEditionMarketplaceRoute: typeof GameGameEditionEditionMarketplaceRoute
  GameGameEditionEditionPredictRoute: typeof GameGameEditionEditionPredictRoute
  GameGameEditionEditionIndexRoute: typeof GameGameEditionEditionIndexRoute
}

const GameGameRouteChildren: GameGameRouteChildren = {
  GameGameAboutRoute: GameGameAboutRoute,
  GameGameActivityRoute: GameGameActivityRoute,
  GameGameGuildsRoute: GameGameGuildsRoute,
  GameGameInventoryRoute: GameGameInventoryRoute,
  GameGameLeaderboardRoute: GameGameLeaderboardRoute,
  GameGameMarketplaceRoute: GameGameMarketplaceRoute,
  GameGamePredictRoute: GameGamePredictRoute,
  GameGameIndexRoute: GameGameIndexRoute,
  GameGameCollectionCollectionRoute:
    GameGameCollectionCollectionRouteWithChildren,
  GameGameEditionEditionAboutRoute: GameGameEditionEditionAboutRoute,
  GameGameEditionEditionActivityRoute: GameGameEditionEditionActivityRoute,
  GameGameEditionEditionGuildsRoute: GameGameEditionEditionGuildsRoute,
  GameGameEditionEditionInventoryRoute: GameGameEditionEditionInventoryRoute,
  GameGameEditionEditionLeaderboardRoute:
    GameGameEditionEditionLeaderboardRoute,
  GameGameEditionEditionMarketplaceRoute:
    GameGameEditionEditionMarketplaceRoute,
  GameGameEditionEditionPredictRoute: GameGameEditionEditionPredictRoute,
  GameGameEditionEditionIndexRoute: GameGameEditionEditionIndexRoute,
}

const GameGameRouteWithChildren = GameGameRoute._addFileChildren(
  GameGameRouteChildren,
)

interface PlayerPlayerRouteChildren {
  PlayerPlayerAchievementsRoute: typeof PlayerPlayerAchievementsRoute
  PlayerPlayerActivityRoute: typeof PlayerPlayerActivityRoute
  PlayerPlayerInventoryRoute: typeof PlayerPlayerInventoryRoute
  PlayerPlayerPositionsRoute: typeof PlayerPlayerPositionsRoute
  PlayerPlayerIndexRoute: typeof PlayerPlayerIndexRoute
}

const PlayerPlayerRouteChildren: PlayerPlayerRouteChildren = {
  PlayerPlayerAchievementsRoute: PlayerPlayerAchievementsRoute,
  PlayerPlayerActivityRoute: PlayerPlayerActivityRoute,
  PlayerPlayerInventoryRoute: PlayerPlayerInventoryRoute,
  PlayerPlayerPositionsRoute: PlayerPlayerPositionsRoute,
  PlayerPlayerIndexRoute: PlayerPlayerIndexRoute,
}

const PlayerPlayerRouteWithChildren = PlayerPlayerRoute._addFileChildren(
  PlayerPlayerRouteChildren,
)

interface GameGamePlayerPlayerRouteChildren {
  GameGamePlayerPlayerAchievementsRoute: typeof GameGamePlayerPlayerAchievementsRoute
  GameGamePlayerPlayerActivityRoute: typeof GameGamePlayerPlayerActivityRoute
  GameGamePlayerPlayerInventoryRoute: typeof GameGamePlayerPlayerInventoryRoute
  GameGamePlayerPlayerPositionsRoute: typeof GameGamePlayerPlayerPositionsRoute
  GameGamePlayerPlayerIndexRoute: typeof GameGamePlayerPlayerIndexRoute
}

const GameGamePlayerPlayerRouteChildren: GameGamePlayerPlayerRouteChildren = {
  GameGamePlayerPlayerAchievementsRoute: GameGamePlayerPlayerAchievementsRoute,
  GameGamePlayerPlayerActivityRoute: GameGamePlayerPlayerActivityRoute,
  GameGamePlayerPlayerInventoryRoute: GameGamePlayerPlayerInventoryRoute,
  GameGamePlayerPlayerPositionsRoute: GameGamePlayerPlayerPositionsRoute,
  GameGamePlayerPlayerIndexRoute: GameGamePlayerPlayerIndexRoute,
}

const GameGamePlayerPlayerRouteWithChildren =
  GameGamePlayerPlayerRoute._addFileChildren(GameGamePlayerPlayerRouteChildren)

interface GameGameEditionEditionCollectionCollectionRouteChildren {
  GameGameEditionEditionCollectionCollectionActivityRoute: typeof GameGameEditionEditionCollectionCollectionActivityRoute
  GameGameEditionEditionCollectionCollectionHoldersRoute: typeof GameGameEditionEditionCollectionCollectionHoldersRoute
  GameGameEditionEditionCollectionCollectionItemsRoute: typeof GameGameEditionEditionCollectionCollectionItemsRoute
  GameGameEditionEditionCollectionCollectionIndexRoute: typeof GameGameEditionEditionCollectionCollectionIndexRoute
}

const GameGameEditionEditionCollectionCollectionRouteChildren: GameGameEditionEditionCollectionCollectionRouteChildren =
  {
    GameGameEditionEditionCollectionCollectionActivityRoute:
      GameGameEditionEditionCollectionCollectionActivityRoute,
    GameGameEditionEditionCollectionCollectionHoldersRoute:
      GameGameEditionEditionCollectionCollectionHoldersRoute,
    GameGameEditionEditionCollectionCollectionItemsRoute:
      GameGameEditionEditionCollectionCollectionItemsRoute,
    GameGameEditionEditionCollectionCollectionIndexRoute:
      GameGameEditionEditionCollectionCollectionIndexRoute,
  }

const GameGameEditionEditionCollectionCollectionRouteWithChildren =
  GameGameEditionEditionCollectionCollectionRoute._addFileChildren(
    GameGameEditionEditionCollectionCollectionRouteChildren,
  )

interface GameGameEditionEditionPlayerPlayerRouteChildren {
  GameGameEditionEditionPlayerPlayerAchievementsRoute: typeof GameGameEditionEditionPlayerPlayerAchievementsRoute
  GameGameEditionEditionPlayerPlayerActivityRoute: typeof GameGameEditionEditionPlayerPlayerActivityRoute
  GameGameEditionEditionPlayerPlayerInventoryRoute: typeof GameGameEditionEditionPlayerPlayerInventoryRoute
  GameGameEditionEditionPlayerPlayerPositionsRoute: typeof GameGameEditionEditionPlayerPlayerPositionsRoute
  GameGameEditionEditionPlayerPlayerIndexRoute: typeof GameGameEditionEditionPlayerPlayerIndexRoute
}

const GameGameEditionEditionPlayerPlayerRouteChildren: GameGameEditionEditionPlayerPlayerRouteChildren =
  {
    GameGameEditionEditionPlayerPlayerAchievementsRoute:
      GameGameEditionEditionPlayerPlayerAchievementsRoute,
    GameGameEditionEditionPlayerPlayerActivityRoute:
      GameGameEditionEditionPlayerPlayerActivityRoute,
    GameGameEditionEditionPlayerPlayerInventoryRoute:
      GameGameEditionEditionPlayerPlayerInventoryRoute,
    GameGameEditionEditionPlayerPlayerPositionsRoute:
      GameGameEditionEditionPlayerPlayerPositionsRoute,
    GameGameEditionEditionPlayerPlayerIndexRoute:
      GameGameEditionEditionPlayerPlayerIndexRoute,
  }

const GameGameEditionEditionPlayerPlayerRouteWithChildren =
  GameGameEditionEditionPlayerPlayerRoute._addFileChildren(
    GameGameEditionEditionPlayerPlayerRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GuildsRoute: GuildsRoute,
  InventoryRoute: InventoryRoute,
  LeaderboardRoute: LeaderboardRoute,
  MarketplaceRoute: MarketplaceRoute,
  PredictRoute: PredictRoute,
  CollectionCollectionRoute: CollectionCollectionRouteWithChildren,
  GameGameRoute: GameGameRouteWithChildren,
  PlayerPlayerRoute: PlayerPlayerRouteWithChildren,
  GameGamePlayerPlayerRoute: GameGamePlayerPlayerRouteWithChildren,
  GameGameEditionEditionCollectionCollectionRoute:
    GameGameEditionEditionCollectionCollectionRouteWithChildren,
  GameGameEditionEditionPlayerPlayerRoute:
    GameGameEditionEditionPlayerPlayerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
