packages:
  - client
  - contracts
  - packages/**
catalog:
  "@cartridge/presets": github:cartridge-gg/presets#e6a5022
  "@cartridge/ui": github:cartridge-gg/ui#0111cc8
  "@cartridge/connector": 0.10.0-alpha.1
  "@cartridge/controller": 0.10.0-alpha.1
  "@starknet-react/core": 5.0.1
  "@starknet-react/chains": 5.0.1
  "@dojoengine/core": 1.7.1
  "@dojoengine/sdk": 1.7.2
  "@dojoengine/torii-client": 1.7.2
  "@dojoengine/torii-wasm": 1.7.2
  "@dojoengine/grpc": 1.7.2
  class-variance-authority: ^0.7.1
  starknet: 8.5.4
  tsup: 8.4.0
  typescript: "5.8"
