export const data = {
  blobert: {
    worldAddress:
      "0x1405692c316d05ac219d844829293d1ff1271fde8fd486e5fe1e68a774b2adb",
    namespace: "amma_blobert",
    project: "ba-pve-dev-alex",
    rpc: "https://api.cartridge.gg/x/starknet/sepolia",
    policies: "",
    color: "#D7B000",
    preset: "blob-arena-amma",
    name: "Blob Arena AMMA",
    description: `Blob Area is a mini-game designed for a game jam, featuring unique characters known as "Bloberts" engaging in strategic, Pokemon-like battles. Players will navigate through exciting encounters, against other players or against AI, using their Bloberts' distinctive traits to outsmart and defeat opponents. The game's core mechanic revolves around an enhanced rock-paper-scissors style combat modified by each character's attributes.`,
    image: "https://static.cartridge.gg/presets/blob-arena-amma/icon.png",
    banner: "https://static.cartridge.gg/presets/blob-arena-amma/cover.png",
    cover: "https://static.cartridge.gg/presets/blob-arena-amma/cover.png",
    discord: "",
    telegram: "",
    twitter: "https://x.com/Blobarena",
    youtube: "",
    website: "https://blobarena.xyz/",
    github: "https://github.com/GrugLikesRocks/Blob-arena",
    videos: "",
    images: "",
  },
  darkshuffle: {
    worldAddress:
      "0x6a9e4c6f0799160ea8ddc43ff982a5f83d7f633e9732ce42701de1288ff705f",
    namespace: "ds_v1_2_0",
    project: "darkshufflebal",
    rpc: "https://api.cartridge.gg/x/starknet/mainnet",
    policies: "",
    color: "#F59100",
    preset: "dark-shuffle",
    name: "Dark Shuffle",
    description:
      "A Provable Roguelike Deck-building Game on Starknet, powered by LORDS.",
    image: "https://static.cartridge.gg/presets/dark-shuffle/icon.svg",
    banner: "https://static.cartridge.gg/presets/dark-shuffle/cover.png",
    cover: "https://static.cartridge.gg/presets/dark-shuffle/cover.png",
    discord: "https://discord.gg/CEXUEJF3",
    telegram: "",
    twitter: "https://x.com/darkshuffle_gg",
    youtube: "",
    website: "https://darkshuffle.io/",
    github: "https://github.com/Provable-Games/dark-shuffle",
    videos: "",
    images: "",
  },
  dopewars: {
    worldAddress:
      "0x4f3dccb47477c087ad9c76b8067b8aadded57f8df7f2d7543e6066bcb25332c",
    namespace: "dopewars",
    project: "dopewarsbal",
    rpc: "https://api.cartridge.gg/x/starknet/mainnet",
    policies: "",
    color: "#11ED83",
    preset: "dope-wars",
    name: "Dope Wars",
    description:
      "Dope Wars is an onchain adaptation of the classic arbitrage game Drug Wars, built by Cartridge in partnership with Dope DAO.",
    image: "https://static.cartridge.gg/presets/dope-wars/icon.png",
    banner: "https://static.cartridge.gg/presets/dope-wars/cover.png",
    cover: "https://static.cartridge.gg/presets/dope-wars/cover.png",
    discord: "https://discord.gg/CEXUEJF3",
    telegram: "",
    twitter: "https://x.com/TheDopeWars",
    youtube: "",
    website: "https://dopewars.game/",
    github: "https://github.com/cartridge-gg/dopewars",
    videos:
      "https://youtu.be/bkNF9VdY2-o?si=Fh2KQLC1-qQmYPlG\nhttps://youtu.be/-ptcWqcGiuo?si=eslLenE0vRqL-bRM\nhttps://youtube.com/shorts/OU8rqBxHdDI?si=mgZ9zLA1wc6OWzfB",
    images:
      "https://repository-images.githubusercontent.com/614510733/32e5253b-7fd6-4e39-b536-9678ee2557bc\nhttps://pbs.twimg.com/media/GI6077pW8AA6wrt?format=jpg&name=large",
  },
  dragark: {
    worldAddress:
      "0x022055481479edc9542aa28bc7da760c45fbf320bce571c31c161baddc13acd9",
    namespace: "dragark",
    project: "dragark-mainnet-v10-1",
    rpc: "https://api.cartridge.gg/x/starknet/mainnet",
    policies: "",
    color: "#71EB34",
    preset: "dragark",
    name: "Dragark",
    description:
      "Dragark Mainnet is live now! Let's dive into the Action: Battle, Upgrade, and Mine for Dragark Stones!",
    image: "https://static.cartridge.gg/presets/dragark/icon.png",
    banner: "https://static.cartridge.gg/presets/dragark/cover.png",
    cover: "https://static.cartridge.gg/presets/dragark/cover.png",
    discord: "https://discord.gg/KEChMrdk7z",
    telegram: "",
    twitter: "https://x.com/playDRAGARK",
    youtube: "",
    website: "https://dragark.net/",
    github: "https://github.com/DragarkTeam/dragark-contract",
    videos: "",
    images: "",
  },
  pistols: {
    worldAddress:
      "0x02ea88c9a6314a10e7d8b6e557d01d68cf72d962707086aa242bc4805071f34d",
    namespace: "pistols",
    project: "pistols-staging",
    rpc: "https://api.cartridge.gg/x/starknet/sepolia",
    policies: "",
    color: "#EF9758",
    preset: "pistols",
    name: "Pistols",
    description: "Fully on-chain game made with Dojo by Underware.gg",
    image: "https://static.cartridge.gg/presets/pistols/icon.png",
    banner: "https://static.cartridge.gg/presets/pistols/cover.png",
    discord: "https://discord.gg/Zbap29dD",
    telegram: "",
    twitter: "https://x.com/underware_gg",
    youtube: "",
    website: "https://pistols.underware.gg/",
    github: "https://github.com/underware-gg/pistols",
    videos: "",
    images: "",
  },
  eternum: {
    worldAddress:
      "0x6a9e4c6f0799160ea8ddc43ff982a5f83d7f633e9732ce42701de1288ff705f",
    namespace: "s0_eternum",
    project: "eternum-prod",
    rpc: "https://api.cartridge.gg/x/starknet/mainnet",
    policies: "",
    color: "#dc8b07",
    preset: "eternum",
    name: "Eternum",
    description: "Rule the Hex.",
    image: "https://static.cartridge.gg/presets/eternum/icon.svg",
    banner: "https://static.cartridge.gg/presets/eternum/cover.png",
    cover: "https://static.cartridge.gg/presets/eternum/cover.png",
    discord: "https://discord.gg/CEXUEJF3",
    telegram: "",
    twitter: "https://x.com/RealmsEternum",
    youtube: "",
    website: "https://eternum.realms.world/",
    github: "https://github.com/BibliothecaDAO/eternum",
    videos: "",
    images: "",
  },
  ponziland: {
    worldAddress:
      "0x628b6af861259ce9ce22e8df6ebd5fbf4fde9a7d4e6eba086aa8dd32325f3b0",
    namespace: "ponzi_land",
    project: "ponziland-tourney",
    rpc: "https://api.cartridge.gg/x/starknet/mainnet",
    policies: "",
    color: "#F38332",
    preset: "ponziland",
    name: "Ponzi Land",
    description:
      "Welcome to the world of Ponzi , where the crypto dreams are limitless, and the meme coins are abundant. Dive into the uncharted territories of blockchain , meet the enigmatic characters behind the schemes, and uncover the secrets of the next big rug pull . Join us in this thrilling journey where fortunes are made and lost, and let your imagination run wild in the fair game of crypto adventures.",
    image: "https://static.cartridge.gg/presets/ponziland/icon.svg",
    banner: "https://static.cartridge.gg/presets/ponziland/cover.png",
    cover: "https://static.cartridge.gg/presets/ponziland/cover.png",
    discord: "https://discord.gg/kKCfH4tE",
    telegram: "",
    twitter: "https://x.com/ponzidotland",
    youtube: "",
    website: "https://play.ponzi.land/",
    github: "https://github.com/RuneLabsxyz/PonziLand",
    videos: "",
    images: "",
  },
  zkube: {
    worldAddress:
      "0x30d5d5c610dd736faea146b20b850af64e34ca6e5c5a66462f76f32f48dd997",
    namespace: "zkube",
    project: "zkubebal",
    rpc: "https://api.cartridge.gg/x/starknet/mainnet",
    policies: "",
    color: "#5bc3e6",
    preset: "zkube",
    name: "zKube",
    description:
      "zKube is an engaging puzzle game that puts players' strategic thinking to the test. Set within a dynamic grid, the objective is simple: manipulate blocks to form solid lines and earn points. Each turn, a new line of blocks emerges from the bottom of the grid, and players have the opportunity to slide any block horizontally to strategically position them. The challenge lies in clearing lines efficiently to prevent the grid from filling up. With no notion of speed or acceleration, zKube offers a purely reflective gameplay experience, allowing players to focus solely on their puzzle-solving skills. Are you ready to dive into the world of zKube and master its captivating challenges?",
    image: "https://static.cartridge.gg/presets/zkube/icon.png",
    banner: "https://static.cartridge.gg/presets/zkube/cover.png",
    cover: "https://static.cartridge.gg/presets/zkube/cover.png",
    discord: "https://discord.gg/dH4gcNxb",
    telegram: "",
    twitter: "https://x.com/zKube_game",
    youtube: "",
    website: "https://app.zkube.xyz/",
    github: "https://github.com/z-korp/zkube",
    videos: "",
    images: "",
  },
};
