name: CI

on:
  push:
  pull_request:

env:
  DOJO_VERSION: v1.4.0
  SCARB_VERSION: 2.9.4
  WORKING_DIRECTORY: ./packages

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check format
    steps:
      - uses: actions/checkout@v4
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: ${{ env.SCARB_VERSION }}
      - name: Format
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: scarb fmt --check
        shell: bash

  build:
    needs: check
    runs-on: ubuntu-latest
    name: Build package
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Build
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: sozo build
        shell: bash

  test:
    needs: [check, build]
    runs-on: ubuntu-latest
    name: Test package
    steps:
      - uses: actions/checkout@v4
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: ${{ env.SCARB_VERSION }}
      - uses: ./.github/actions/setup
      - name: Test
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: sozo test
        shell: bash
